import { Injectable } from '@nestjs/common';
import type { MessageSource } from '@repo/shared';
import { SupabaseService } from '../../common/supabase/supabase.service';

export interface NewChunk {
  chunkIndex: number;
  chunkText: string;
  embedding: number[];
}

export interface RetrievedChunk {
  id: string;
  documentId: string;
  documentTitle: string;
  chunkText: string;
  similarity: number;
}

@Injectable()
export class ChunksRepository {
  constructor(private readonly supabase: SupabaseService) {}

  /**
   * Atomically replace a document's chunks via a single RPC so a concurrent
   * read never sees a half-written state. Embeddings are generated by the
   * caller BEFORE this runs, so a provider failure never reaches here.
   */
  async replaceForDocument(documentId: string, chunks: NewChunk[]): Promise<void> {
    const { error } = await this.supabase.admin.rpc('replace_document_chunks', {
      p_document_id: documentId,
      p_chunks: chunks.map((c) => ({
        chunk_index: c.chunkIndex,
        chunk_text: c.chunkText,
        embedding: c.embedding,
      })),
    });
    if (error) throw new Error(`replaceForDocument failed: ${error.message}`);
  }

  /** Top-k cosine similarity search, scoped to the user's own documents. */
  async search(
    queryEmbedding: number[],
    userId: string,
    matchCount = 5,
  ): Promise<RetrievedChunk[]> {
    const { data, error } = await this.supabase.admin.rpc('match_document_chunks', {
      query_embedding: queryEmbedding,
      match_count: matchCount,
      filter_user_id: userId,
    });
    if (error) throw new Error(`search failed: ${error.message}`);
    return (data as Array<{
      id: string;
      document_id: string;
      document_title: string;
      chunk_text: string;
      similarity: number;
    }>).map((r) => ({
      id: r.id,
      documentId: r.document_id,
      documentTitle: r.document_title,
      chunkText: r.chunk_text,
      similarity: r.similarity,
    }));
  }

  /** Map retrieved chunks to the citation shape stored on assistant messages. */
  static toSources(chunks: RetrievedChunk[]): MessageSource[] {
    return chunks.map((c) => ({
      chunkId: c.id,
      documentId: c.documentId,
      documentTitle: c.documentTitle,
      excerpt: c.chunkText.slice(0, 240),
    }));
  }
}
