-- Atomic chunk swap for a document.
--
-- The entire function body runs in a single transaction, so a concurrent
-- reader (a chat request retrieving chunks) sees either the complete old set
-- or the complete new set — never a half-written state. Embeddings are
-- generated by the application BEFORE calling this, so the provider can never
-- fail mid-swap.
--
-- p_chunks is a jsonb array of:
--   { "chunk_index": int, "chunk_text": text, "embedding": number[] }
create or replace function public.replace_document_chunks(
  p_document_id uuid,
  p_chunks      jsonb
)
returns void
language plpgsql
as $$
begin
  delete from public.document_chunks where document_id = p_document_id;

  insert into public.document_chunks (document_id, chunk_index, chunk_text, embedding)
  select
    p_document_id,
    (e->>'chunk_index')::int,
    e->>'chunk_text',
    (e->'embedding')::text::extensions.vector
  from jsonb_array_elements(coalesce(p_chunks, '[]'::jsonb)) as e;
end;
$$;
